language: node_js
node_js:
  - '10'

before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
    - master

after_script:
  - bash ./telegram_notification.sh

deploy:
  provider: heroku
  app: teamy-app
  api_key:
    secure: SpYlsFS9WzZnRRIADFnpBhUGmWaZR9BCr7tnmQXeSJU8dck65FFXYKbT/Hl1QF2Igt1TedNvSMmFZ7rlhl7EOIwYpCLw1fpOP407NSsVxYCmDya+FY8/DAz8FGeFKulhBjuOmPuYL4S6ssOjAR6fn27v2BkZlw38tFQkF7k7yoDkGIm05suQngwwSaQTFzIbdqTPV7qtSd6kZNEQ3Jr++93m5Fjy7g5NYNI5y3h9QBfzSXTworBq1RRTYGZwQ/bEWkS90iNK0NT2o5sqcUwT/ALdTVI21LsZ7jzfX5/pJFQ2wuGbRxT6lmP/XwGS8yjIh3NrSZj7jLQh8eKZabFdLyHxPl1G90bcrs75NfflA4RO0LlKIh849q/xYrmer9xd5j88i91K5J5E+GYxFMjEcWmBZzXUmlGmg37CrBl5YO9ulVfTI6105F/DA+X46wFA59HCR3c+5kxciNXGyrHEbHJSNMsL1hAcV7XS4+j7L8LcZa8+4FsKd5tusrYysM06dsJq2zgFAS6zFyvonGfMaZB13JdQAv+Q0bp6Md/7+ID3Jl2LRuBXyuVOOgZAvt179NVn1hsfClm/lvt3dbbr4KAhQccZl5ULK0C9i3bqjdRltPTaMvwVBoPb/CssNe86Amo7zB56477dA5jakAKeEfEgcfxQmt1+qrSJW2nFskM=

